# Generated by Django 6.0.1 on 2026-02-01 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=16)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('nama_ibu_kandung', models.CharField(blank=True, max_length=150)),
                ('nip_nuptk', models.CharField(blank=True, max_length=30)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('pangkat_golongan', models.CharField(blank=True, max_length=50)),
                ('nama_sekolah', models.CharField(blank=True, max_length=200)),
                ('npsn', models.CharField(blank=True, max_length=20)),
                ('alamat_sekolah', models.TextField(blank=True)),
                ('email_unit_kerja', models.EmailField(blank=True, max_length=254)),
                ('alamat_rumah', models.TextField(blank=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('email_pribadi', models.EmailField(blank=True, max_length=254)),
                ('pendidikan_terakhir', models.CharField(blank=True, max_length=100)),
                ('jurusan', models.CharField(blank=True, max_length=100)),
                ('gelar', models.CharField(blank=True, max_length=50)),
                ('scan_ktp', models.FileField(blank=True, null=True, upload_to='documents/ktp/')),
                ('scan_kk', models.FileField(blank=True, null=True, upload_to='documents/kk/')),
                ('scan_sk', models.FileField(blank=True, null=True, upload_to='documents/sk/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
