# Generated by Django 6.0.1 on 2026-02-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
