# Generated by Django 4.2.28 on 2026-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/students/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='ijazah',
            field=models.FileField(blank=True, null=True, upload_to='documents/students/ijazah/'),
        ),
    ]
