# Generated by Django 6.0.3 on 2026-03-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_studentprofile_foto_studentprofile_ijazah'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='scan_kk',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scan_ktp',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='scan_sk',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/teachers/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ijazah',
            field=models.FileField(blank=True, null=True, upload_to='documents/teachers/ijazah/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='scan_kk',
            field=models.FileField(blank=True, null=True, upload_to='documents/teachers/kk/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='scan_ktp',
            field=models.FileField(blank=True, null=True, upload_to='documents/teachers/ktp/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='scan_sk',
            field=models.FileField(blank=True, null=True, upload_to='documents/teachers/sk/'),
        ),
    ]
