# Generated by Django 4.2.28 on 2026-02-24 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_nama_lengkap'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip_nuptk', models.CharField(max_length=30, unique=True)),
                ('jabatan', models.CharField(max_length=100)),
                ('pangkat_golongan', models.CharField(blank=True, max_length=50)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_detail', to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('kelas', models.CharField(max_length=20)),
                ('nama_ibu_kandung', models.CharField(blank=True, max_length=150)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_detail', to='accounts.userprofile')),
            ],
        ),
    ]
