# Generated by Django 4.2.28 on 2026-02-25 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_teacherprofile_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nip_nuptk',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pangkat_golongan',
        ),
    ]
