# Generated by Django 4.2.28 on 2026-02-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_userprofile_jabatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='nip_nuptk',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
