# Generated by Django 4.2.28 on 2026-02-28 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_matapelajaran_rename_name_classroom_nama_and_more'),
        ('accounts', '0006_alter_teacherprofile_nip_nuptk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classroom'),
        ),
    ]
