# Generated by Django 6.0.3 on 2026-03-24 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('nisn', models.CharField(max_length=20)),
                ('nik', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=25)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('no_registrasi', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('nama_ibu_kandung', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/registration/')),
                ('ijazah', models.FileField(blank=True, null=True, upload_to='documents/ijazah/')),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('asal_sekolah', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('nik', models.CharField(blank=True, max_length=16)),
                ('nisn', models.CharField(max_length=20, unique=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/students/')),
                ('ijazah', models.FileField(blank=True, null=True, upload_to='documents/students/ijazah/')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('nama_ibu_kandung', models.CharField(blank=True, max_length=100)),
                ('alamat_rumah', models.TextField(blank=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('email_pribadi', models.EmailField(blank=True, max_length=254)),
                ('status_akademik', models.CharField(choices=[('aktif', 'Aktif'), ('lulus', 'Lulus'), ('drop', 'Putus Sekolah')], default='aktif', max_length=20)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
