# Generated by Django 4.2.28 on 2026-03-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20)),
                ('nisn', models.CharField(max_length=20)),
                ('nik', models.CharField(max_length=20)),
                ('tempat_lahir', models.CharField(max_length=25)),
                ('birth_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('asal_sekolah', models.TextField()),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Diterima'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='active', max_length=20)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.classroom')),
            ],
        ),
    ]
