# Generated by Django 4.2.28 on 2026-03-09 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='photos/registration/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='ijazah',
            field=models.FileField(blank=True, null=True, upload_to='documents/ijazah/'),
        ),
        migrations.AddField(
            model_name='registration',
            name='nama_ibu_kandung',
            field=models.CharField(default='belum diisi', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='no_registrasi',
            field=models.CharField(blank=True, editable=False, max_length=20, unique=True),
        ),
    ]
