# Generated by Django 4.2.28 on 2026-03-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_registration_foto_registration_ijazah_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='nama_ibu_kandung',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
