# Generated by Django 4.2.28 on 2026-03-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_registration_nama_ibu_kandung'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
    ]
