# Generated by Django 6.0.3 on 2026-03-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_studentprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='alamat_rumah',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email_pribadi',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='nik',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
