# Generated by Django 6.0.3 on 2026-03-17 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0002_alter_attendance_student'),
        ('grades', '0002_alter_grade_student'),
        ('students', '0007_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='status_akademik',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('lulus', 'Lulus'), ('drop', 'Putus Sekolah')], default='aktif', max_length=20),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
