# Generated by Django 6.0.3 on 2026-03-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studentprofile_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='nama_ibu_kandung',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
