# Generated by Django 4.2.28 on 2026-03-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='RA. Al-Marzuqiyah', max_length=200)),
                ('address', models.TextField()),
                ('google_maps_url', models.TextField(help_text='Masukkan link iframe src dari Google Maps')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
