# Generated by Django 6.0.3 on 2026-03-24 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('nik', models.CharField(blank=True, max_length=16)),
                ('nip_nuptk', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/teachers/')),
                ('ijazah', models.FileField(blank=True, null=True, upload_to='documents/teachers/ijazah/')),
                ('nama_ibu_kandung', models.CharField(blank=True, max_length=100)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('no_hp', models.CharField(blank=True, max_length=20)),
                ('email_pribadi', models.EmailField(blank=True, max_length=254)),
                ('alamat_rumah', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('pindah', 'Pindah'), ('resign', 'Mengundurkan diri')], default='aktif', max_length=20)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academics.classroom')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
