# Generated by Django 6.0.3 on 2026-03-16 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_lengkap', models.CharField(max_length=255)),
                ('nip_nuptk', models.CharField(blank=True, max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='photos/teachers/')),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tanggal_lahir', models.DateField(blank=True, null=True)),
                ('alamat', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
