# Generated by Django 6.0.3 on 2026-03-19 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('teachers', '0002_teacherprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='alamat',
            new_name='alamat_rumah',
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academics.classroom'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='email_pribadi',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='ijazah',
            field=models.FileField(blank=True, null=True, upload_to='documents/teachers/ijazah/'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='nama_ibu_kandung',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='nik',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='status',
            field=models.CharField(choices=[('aktif', 'Aktif'), ('pindah', 'Pindah'), ('resign', 'Mengundurkan diri')], default='aktif', max_length=20),
        ),
    ]
